<%@ Page Title="Delete Route" Language="C#" MasterPageFile="~/TransportManager.Master" AutoEventWireup="true" CodeBehind="DeleteRoute.aspx.cs" Inherits="TransportManagementSystemFYP.DeleteRoute" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <script type="text/javascript">
        function massege() {
            swal({
                title: 'Are you sure!',
                text: 'After this route will be remove from system',
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#987463',
            },
            function () {
                window.location.href = 'DeleteRoute.aspx';
            });
        }
    </script>
    <div class="contact w3l-2">
		<div class="container">
			<h2 class="w3ls_head">Delete <span>Route</span></h2>
				<div class="contact-grids">
                    <div class="col-lg-12 contact-grid agileinfo-5">               
                        <asp:TextBox ID="SearchTextBox" placeholder="Enter route to search..." CssClass="form-control" type="search" required="" runat="server"></asp:TextBox> 
                        <asp:Button ID="BtnSearchRoute" CssClass="btn pull-right" runat="server" Text="Search Route" OnClick="BtnSearchRoute_Click" />
                         </div>
                    <div class="clearfix"></div>
                      <br />
                    <div class="col-md-12 contact-grid agileinfo-5">
                        <asp:GridView ID="GridView" DataKeyNames="RouteID" AutoGenerateDeleteButton="true" OnRowDeleting="GridView_RowDeleting"
                              runat="server" CssClass="mydatagrid" PagerStyle-CssClass="pager"
                             HeaderStyle-CssClass="header" RowStyle-CssClass="rows" AllowPaging="True" >
                        </asp:GridView>
                         <br />
                        </div>					
						<div class="clearfix"></div>
				</div>
		</div>
	</div>
</asp:Content>
