<%@ Page Title="Delete Driver" Language="C#" MasterPageFile="~/TransportManager.Master" AutoEventWireup="true" CodeBehind="DeleteDriver.aspx.cs" Inherits="TransportManagementSystemFYP.DeleteDriver" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="contact w3l-2">
        <div class="container">
            <h2 class="w3ls_head">Delete <span>Driver</span></h2>
            <div class="contact-grids">
                <div class="col-lg-12 contact-grid agileinfo-5">
                    <asp:TextBox ID="SearchTextBox" placeholder="Enter driver to search..." CssClass="form-control" type="search" required="" runat="server"></asp:TextBox>
                    <asp:Button ID="BtnSearchDriver" CssClass="btn pull-right" runat="server" Text="Search Driver" OnClick="BtnSearchDriver_Click" />
                </div>
                <div class="clearfix"></div>
                <br />
                <div class="col-md-12 contact-grid agileinfo-5">
                    <asp:GridView ID="GridView" DataKeyNames="DriverID" AutoGenerateDeleteButton="true"
                        OnRowDeleting="GridView_RowDeleting"
                        runat="server" CssClass="mydatagrid" PagerStyle-CssClass="pager"
                        HeaderStyle-CssClass="header" RowStyle-CssClass="rows" AllowPaging="True">
                    </asp:GridView>
                    <br />
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</asp:Content>
